### Хочу сначала отобрать признаки. Признаки с низкой дисперсией скорее всего менее информативны, поэтому, сначала сделаю отбор по дисперсии. В следующем ноутбуке хочу попробовать SBS алгоритм.

In [1]:
import numpy as np
from gzip import open # NB: overrides standard open()
import pickle as pkl
import tensorly as tl
from tensorly.base import tensor_to_vec,  partial_tensor_to_vec
import pandas as pd
import warnings 
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import GridSearchCV
import matplotlib as mpl
from glob import glob
import os
import math
import functools
from sklearn.base import BaseEstimator
from sklearn.base import RegressorMixin

In [2]:
warnings.simplefilter('ignore') # отключим предупреждения Anaconda

In [3]:
Xdata_numpy = pkl.load(open('C:/Users/admin/Desktop/PLS2021/N-PLS/X_new.pkl.gz', 'rb'))
Ydata = pkl.load(open('C:/Users/admin/Desktop/PLS2021/N-PLS/y.pkl.gz', 'rb'))
print(Xdata_numpy['emission'].shape)

(206,)


In [4]:
Xdata_numpy['excitation']

array([245., 250., 255., 260., 265., 270., 275., 280., 285., 290., 295.,
       300., 305., 310., 315., 320., 325., 330., 335., 340., 345., 350.,
       355., 360., 365., 370., 375., 380., 385., 390., 395., 400., 405.,
       410., 415., 420., 425., 430., 435., 440., 445., 450., 455., 460.,
       465., 470., 475., 480., 485., 490., 495., 500.])

In [5]:
X_big=Xdata_numpy['X']

In [6]:
(X_big.mean(axis=0)).shape

(206, 52)

In [7]:
X_big[:,50,8]

array([0.65146595, 1.04989102, 0.45439327, 0.83234159, 0.94569607,
       0.87379848, 0.25354816, 1.28721509, 0.75324228, 1.06003262,
       0.41105254, 1.05576681, 1.27723665, 1.4299822 , 1.44627517,
       0.38409103, 1.28565132, 0.71377399, 0.54094439, 0.53461583,
       0.9341003 , 0.98641663, 1.15157006, 0.9252526 , 0.26309461,
       0.62352113, 0.85551931, 0.42271355, 0.5376293 , 0.51435184,
       0.50412126, 0.84849171, 0.71693687, 0.62951692, 0.82833542])

In [8]:
X_big[:,50,8].mean()

0.7995024560851044

In [9]:
X_big[:,50,8]-X_big[:,50,8].mean()

array([-0.14803651,  0.25038856, -0.34510918,  0.03283913,  0.14619361,
        0.07429603, -0.54595429,  0.48771264, -0.04626018,  0.26053016,
       -0.38844991,  0.25626435,  0.47773419,  0.63047974,  0.64677271,
       -0.41541142,  0.48614887, -0.08572846, -0.25855807, -0.26488663,
        0.13459784,  0.18691417,  0.3520676 ,  0.12575014, -0.53640785,
       -0.17598133,  0.05601685, -0.3767889 , -0.26187316, -0.28515062,
       -0.2953812 ,  0.04898926, -0.08256559, -0.16998553,  0.02883296])

In [10]:
(X_big[:,50,8]-X_big[:,50,8].mean())**2

array([0.02191481, 0.06269443, 0.11910035, 0.00107841, 0.02137257,
       0.0055199 , 0.29806609, 0.23786361, 0.00214   , 0.06787596,
       0.15089334, 0.06567142, 0.22822996, 0.39750471, 0.41831494,
       0.17256665, 0.23634072, 0.00734937, 0.06685227, 0.07016493,
       0.01811658, 0.03493691, 0.1239516 , 0.0158131 , 0.28773338,
       0.03096943, 0.00313789, 0.14196988, 0.06857755, 0.08131087,
       0.08725005, 0.00239995, 0.00681708, 0.02889508, 0.00083134])

In [11]:
sum((X_big[:,50,8]-X_big[:,50,8].mean())**2)

3.5842251112831938

In [12]:
import  subprocess
import sys
import os
from PLS1_help_scripts.variable_wave import firstSellectionVariables

In [13]:
a=firstSellectionVariables()

In [14]:
t=a.variance(X_big.copy())

In [16]:
tt=a.selectionExctationWave(X_big.copy(),Xdata_numpy['excitation'],Xdata_numpy['emission'])

In [17]:
tt.get_params

<bound method BaseEstimator.get_params of firstSellectionVariables(var_emission=0.2, var_excitation=0.01)>

In [18]:
tt.x_new_.shape

(35, 30, 11)